# Generated by Django 4.2.7 on 2023-11-05 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_userprofile_unique_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='unique_code',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, unique=True),
        ),
    ]
