# Generated by Django 4.2.7 on 2023-11-05 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_userprofile_unique_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='completion_date',
            field=models.DateField(default='2023-11-05'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='course_name',
            field=models.CharField(default='Live Full Stack Open Source Cohort', max_length=255),
        ),
    ]
